{
   'name':'School Library',
   'category': 'website',
    'author': 'safia alqadi',
    'version': '1.0',
    'summary': 'This app helps manage library books, student borrowing, and inventory. Features include book tracking, student management, and real-time updates on available books and overdue items..',
    'depends': ['account','mail','base','website'],
    'data':[
          'security/security.xml',
          'webforms/author_web_form.xml',
          'webforms/category_web_form.xml',
          'webforms/library_categories_list.xml',
          'webforms/library_students_list.xml',
          'webforms/library_books_list.xml',
          'webforms/library_order_web_form.xml',
          'webforms/book_web_form.xml',
          'webforms/library_authors_list.xml',
          'security/ir.model.access.csv',
          'views2/books_view.xml',
          'views2/category_view.xml',
          'views2/orders_view.xml',
          'views2/order_line_view.xml',
          'views2/students_view.xml',
          'views2/authors_view.xml',
          'views2/report_returndstatuse_weekly.xml',
          'views2/order_invoice_.xml',
          'actions/book_action.xml',
          'data/library_book_order_sequence.xml',
          'views2/order_calnedar.xml',
          'views2/library_menu.xml',
          'views2/custom_invoice_view.xml',
          'views2/custom_invoice_line_view.xml',
          'report/report_returnd_weekly.xml',
          'report/report_returndstatuse_weekly.xml',
          'actions/category_action.xml',
          'actions/order_action.xml',
          'actions/student_action.xml',
          'actions/order_line_action.xml',
          'actions/author_action.xml',
          'actions/report_returnd_weekly.xml',
          'actions/top_ten_books.xml',
          'actions/top_ten_student.xml',
          'actions/order_invoice_action.xml',
    ],
'assets': {
   'web._assets_primary_variables': [
      ('prepend', 'school_library/static/src/scss/primary_variables.scss'),
   ],
},
   'installable': True,
   'application': True,
}